apiVersion: v1
kind: Pod
metadata:
  name: nginx-pvc-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-storage
      mountPath: /usr/share/nginx/html

  volumes:
  - name: nginx-storage
    persistentVolumeClaim:
      claimName: nginx-pvc